[package]
name = "nameless"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
publish = false

[features]
default = ["nameless-derive"]

[dependencies]
lazy_static = "1.0"
nameless-derive = { path = "../nameless-derive", version = "0.1.0", optional = true }
