[package]
name = "lambdapi"
version = "0.1.0"
readme = "README.md"
license = "Apache-2.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "An implementation of the LambdaPi type system in Rust"
publish = false

[features]
repl = ["rustyline"]

[[bin]]
name = "repl"
required-features = ["repl"]

[dependencies]
lalrpop-util = "0.14.0"
lazy_static = "1.0"
pretty = "0.3.2"
regex = "0.2.0"
rpds = "0.3.0"
rustyline = { version = "1.0.0", optional = true }

[build-dependencies]
lalrpop = "0.14.0"

[dev-dependencies]
pretty_assertions = "0.4.0"
