[package]
name = "lambdapi"
version = "0.1.0"
readme = "README.md"
license = "Apache-2.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "An implementation of the LambdaPi type system in Rust"
publish = false

[workspace]
members = [
    "source",
]

[features]
bin = ["rustyline", "structopt"]

[[bin]]
name = "lambdapi"
required-features = ["bin"]

[dependencies]
failure = "0.1.1"
lalrpop-util = "0.14.0"
lazy_static = "1.0"
pretty = "0.3.2"
regex = "0.2.0"
rpds = "0.3.0"
rustyline = { version = "1.0.0", optional = true }
source = { path = "./source" }
structopt = { version = "0.2.2", optional = true }
unicode-xid = "0.0.4"

[build-dependencies]
lalrpop = "0.14.0"

[dev-dependencies]
pretty_assertions = "0.4.0"
