[package]
name = "source"
version = "0.1.0"
readme = "README.md"
license = "Apache-2.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "An implementation of the LambdaPi type system in Rust"
publish = false


[dependencies]
termcolor = "0.3.4"
